@startuml "Mpk Class Diagram"
class Person
class Driver
class Controller
class Passenger
class Bank{
    authorizePayment()
}
class TicketValidator{
    'validate(t:Ticket)
    validate(Ticket)
}
class TicketMachine{
    sellTicket(): Ticket
}
class Ticket{
    validated: bool
    tiemstamp
}
class Vehicle{
    'doors: Door[]
    start()
    stop()
}
class Bus
class Door{
    -isOpen: bool
    +open()
    +close()
    +isOpen(): bool
}
class Stop{}
class Course {}

Driver --|> Person
Controller --|> Person
Bus --|> Vehicle
Vehicle "doors" *-- Door
Driver -right- Vehicle
Passenger "vehicle" -down--* "passengers" Vehicle
Passenger *-left- Ticket
TicketValidator --* Vehicle
TicketMachine --* Vehicle
TicketMachine -up- Bank
Controller --* Vehicle
Course *-- Stop
Vehicle -- Course
Passenger "fomal_stop" -- Stop
@enduml